apiVersion: v1
kind: Route
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/tls-acme-secretname: prometheus-telemeter-acme
  name: prometheus-telemeter
  namespace: telemeter
spec:
  port:
    targetPort: https
  tls:
    termination: Reencrypt
  to:
    kind: Service
    name: prometheus-telemeter
