apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: benchmark
  name: benchmark
  namespace: telemeter-benchmark
spec:
  baseImage: quay.io/prometheus/prometheus
  nodeSelector:
    beta.kubernetes.io/os: linux
  replicas: 1
  resources:
    requests:
      memory: 400Mi
  ruleSelector:
    matchLabels:
      prometheus: benchmark
      role: alert-rules
  securityContext: {}
  serviceAccountName: prometheus-benchmark
  serviceMonitorSelector:
    matchLabels:
      k8s-app: telemeter-server
  version: v2.7.1
