apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-benchmark
  namespace: telemeter-benchmark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-benchmark
subjects:
- kind: ServiceAccount
  name: prometheus-benchmark
  namespace: telemeter-benchmark
