apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-benchmark-config
  namespace: telemeter-benchmark
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
