apiVersion: v1
kind: Route
metadata:
  name: prometheus-benchmark
  namespace: telemeter-benchmark
spec:
  port:
    targetPort: web
  tls:
    insecureEdgeTerminationPolicy: Allow
    termination: edge
  to:
    kind: Service
    name: prometheus-benchmark
