apiVersion: v1
data:
  tokens.json: W3sidG9rZW4iOiAiYmVuY2htYXJrIn1d
  whitelist: e19fbmFtZV9fPSJ1cCJ9CntfX25hbWVfXz0iY2x1c3Rlcl92ZXJzaW9uIn0Ke19fbmFtZV9fPSJjbHVzdGVyX3ZlcnNpb25fYXZhaWxhYmxlX3VwZGF0ZXMifQp7X19uYW1lX189ImNsdXN0ZXJfb3BlcmF0b3JfdXAifQp7X19uYW1lX189ImNsdXN0ZXJfb3BlcmF0b3JfY29uZGl0aW9ucyJ9CntfX25hbWVfXz0iY2x1c3Rlcl92ZXJzaW9uX3BheWxvYWQifQp7X19uYW1lX189ImNsdXN0ZXJfdmVyc2lvbl9wYXlsb2FkX2Vycm9ycyJ9CntfX25hbWVfXz0iZXRjZF9vYmplY3RfY291bnRzIn0Ke19fbmFtZV9fPSJhbGVydHMiLGFsZXJ0c3RhdGU9ImZpcmluZyJ9CntfX25hbWVfXz0iY29kZTphcGlzZXJ2ZXJfcmVxdWVzdF9jb3VudDpyYXRlOnN1bSJ9CntfX25hbWVfXz0ia3ViZV9wb2Rfc3RhdHVzX3JlYWR5OmV0Y2Q6c3VtIn0Ke19fbmFtZV9fPSJrdWJlX3BvZF9zdGF0dXNfcmVhZHk6aW1hZ2VfcmVnaXN0cnk6c3VtIn0Ke19fbmFtZV9fPSJjbHVzdGVyOmNhcGFjaXR5X2NwdV9jb3JlczpzdW0ifQp7X19uYW1lX189ImNsdXN0ZXI6Y2FwYWNpdHlfbWVtb3J5X2J5dGVzOnN1bSJ9CntfX25hbWVfXz0iY2x1c3RlcjpjcHVfdXNhZ2VfY29yZXM6c3VtIn0Ke19fbmFtZV9fPSJjbHVzdGVyOm1lbW9yeV91c2FnZV9ieXRlczpzdW0ifQp7X19uYW1lX189Im9wZW5zaGlmdDpjcHVfdXNhZ2VfY29yZXM6c3VtIn0Ke19fbmFtZV9fPSJvcGVuc2hpZnQ6bWVtb3J5X3VzYWdlX2J5dGVzOnN1bSJ9CntfX25hbWVfXz0iY2x1c3Rlcjpub2RlX2luc3RhbmNlX3R5cGVfY291bnQ6c3VtIn0=
kind: Secret
metadata:
  labels:
    k8s-app: telemeter-server
  name: telemeter-server
  namespace: telemeter-benchmark
type: Opaque
