apiVersion: v1
kind: Service
metadata:
  labels:
    prometheus: benchmark
  name: prometheus-benchmark
  namespace: telemeter-benchmark
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  selector:
    app: prometheus
    prometheus: benchmark
  type: ClusterIP
