apiVersion: v1
data:
  rhd.client_id: ""
  rhd.password: ""
  rhd.url: ""
  rhd.username: ""
kind: Secret
metadata:
  labels:
    k8s-app: telemeter-server
  name: telemeter-server
  namespace: telemeter
type: Opaque
