apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: telemeter-client
  name: telemeter-client
  namespace: openshift-monitoring
spec:
  clusterIP: None
  ports:
  - name: http
    port: 8080
    targetPort: http
  selector:
    k8s-app: telemeter-client
