kind: List
apiVersion: v1
items:
- kind: Service
  apiVersion: v1
  metadata:
    name: telemeter
  spec:
    clusterIP: None
    selector:
      app: telemeter
    ports:
    - name: http
      port: 8080
      targetPort: external
- kind: Service
  apiVersion: v1
  metadata:
    name: telemeter-cluster
    annotations:
       service.alpha.openshift.io/serving-cert-secret-name: telemeter-shared
  spec:
    clusterIP: None
    selector:
      app: telemeter
    ports:
    - name: internal
      port: 8081
      targetPort: internal
    - name: cluster
      port: 8082
      targetPort: cluster
- kind: StatefulSet
  apiVersion: apps/v1
  metadata:
    name: telemeter
  spec:
    podManagementPolicy: Parallel
    serviceName: telemeter-cluster
    selector:
      matchLabels:
        app: telemeter
    template:
      metadata:
        labels:
          app: telemeter
      spec:
        volumes:
        - name: tls
          secret:
            secretName: telemeter-shared
        - name: local
          emptyDir: {}
        containers:
        - name: server
          image: registry.svc.ci.openshift.org/ci/telemeter:latest
          volumeMounts:
          - name: tls
            mountPath: /etc/pki/service
          - name: local
            mountPath: /var/lib/telemeter
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8080
          ports:
          - containerPort: 8080
            name: external
          - containerPort: 8081
            name: internal
          - containerPort: 8082
            name: cluster
          env:
          - name: NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          command:
          - /usr/bin/telemeter-server
          - --join=telemeter-cluster
          - --name=$(NAME)
          - --listen=0.0.0.0:8080
          - --listen-internal=0.0.0.0:8081
          - --listen-cluster=0.0.0.0:8082
          - --storage-dir=/var/lib/telemeter
          - --shared-key=/etc/pki/service/tls.key