apiVersion: v1
data:
  match-rules: e19fbmFtZV9fPSJ1cCJ9CntfX25hbWVfXz0ib3BlbnNoaWZ0X2J1aWxkX2luZm8ifQp7X19uYW1lX189Im1hY2hpbmVfY3B1X2NvcmVzIn0Ke19fbmFtZV9fPSJtYWNoaW5lX21lbW9yeV9ieXRlcyJ9CntfX25hbWVfXz0iZXRjZF9vYmplY3RfY291bnRzIn0Ke19fbmFtZV9fPSJBTEVSVFMiLGFsZXJ0c3RhdGU9ImZpcmluZyJ9
  salt: ""
  to: aHR0cHM6Ly9pbmZvZ3cuYXBpLm9wZW5zaGlmdC5jb20=
  token: ""
kind: Secret
metadata:
  labels:
    k8s-app: telemeter-client
  name: telemeter-client
  namespace: openshift-monitoring
type: Opaque
